# Audio classification

In [1]:
# !pip install tensorflow
# !pip install tensorflow-gpu
# !pip install tensorflow-io

In [2]:
import os
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_io as tfio

## 1. Load data

### 1.1 Locate files

In [3]:
# locate all bird clips
capuchin_clips = os.listdir("data/Parsed_Capuchinbird_Clips")
non_capuchin_clips = os.listdir("data/Parsed_Not_Capuchinbird_Clips")
non_capuchin_clips[:3] # returns a list of birt clips

['tawny-owl-sounds-3.wav',
 'cardinal-bird-call-3.wav',
 'Crickets-chirping-at-night-6.wav']

In [4]:
# define paths to files
CAPUCHIN = os.path.join("data/Parsed_Capuchinbird_Clips",capuchin_clips[1])
NON_CAPUCHIN = os.path.join("data/Parsed_Non_Capuchinbird_Clips",non_capuchin_clips[1])
CAPUCHIN # return the full audio path

'data/Parsed_Capuchinbird_Clips/XC22397-2.wav'

### 1.2 Loading audio as tensor

In [5]:
# Read encoded wave file
file_content = tf.io.read_file(CAPUCHIN)

In [6]:
# Decode wav file in single channel
wav, sample_rate = tf.audio.decode_wav(file_content, desired_channels=1)

In [7]:
wav

<tf.Tensor: shape=(120000, 1), dtype=float32, numpy=
array([[ 0.05886841],
       [ 0.0647583 ],
       [ 0.06713867],
       ...,
       [ 0.00158691],
       [-0.00256348],
       [-0.00701904]], dtype=float32)>

In [8]:
sample_rate

<tf.Tensor: shape=(), dtype=int32, numpy=48000>

In [9]:
# remove trailing axis
wav = tf.squeeze(wav, axis= -1)
sample_rate = tf.cast(sample_rate, dtype=tf.int64)

In [10]:
wav

<tf.Tensor: shape=(120000,), dtype=float32, numpy=
array([ 0.05886841,  0.0647583 ,  0.06713867, ...,  0.00158691,
       -0.00256348, -0.00701904], dtype=float32)>

In [11]:
sample_rate

<tf.Tensor: shape=(), dtype=int64, numpy=48000>

In [13]:
tfio.audio.resample(wav, rate_in=sample_rate, rate_out=16000)


NotImplementedError: in user code:

    File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/tensorflow_io/python/ops/audio_ops.py", line 465, in f
        return core_ops.io_audio_resample(
    File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/tensorflow_io/python/ops/__init__.py", line 88, in __getattr__
        return getattr(self._load(), attrb)
    File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/tensorflow_io/python/ops/__init__.py", line 84, in _load
        self._mod = _load_library(self._library)
    File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/tensorflow_io/python/ops/__init__.py", line 69, in _load_library
        raise NotImplementedError(

    NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['/opt/homebrew/anaconda3/lib/python3.11/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
    caused by: ["dlopen(/opt/homebrew/anaconda3/lib/python3.11/site-packages/tensorflow_io/python/ops/libtensorflow_io.so, 0x0006): symbol not found in flat namespace '__ZNK10tensorflow4data11DatasetBase8FinalizeEPNS_15OpKernelContextENSt3__18functionIFN3tsl8StatusOrINS6_4core11RefCountPtrIS1_EEEEvEEE'"]
